### ISSUE TITLE
getting odd base64 illegal character msg in k8s when apply -f .

### ISSUE THREAD

**Issue by jordo1138** [zerda/kube-fluentd-cloudwatch#1]
![errorgh](https://user-images.githubusercontent.com/8525512/33872248-eb90348a-deca-11e7-88ec-6fd66d507e4f.JPG)

i edited the yaml file with my region and keys ... anything I'm missing here?

**Comment by zerda** [comment]
Every item in Kubernetes [Secret](https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually) must be base64 encoded, like this.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
```

**Comment by jordo1138** [comment]
Yes,
I simply edit your yaml file in the repo and take out “redacted” and type
in mine... that’s when I got the error when deploying
Is editing the yaml ruining the encoding?
Thanks

**Comment by zerda** [comment]
Not the file encoding, you should replace **REDACTED** with aws id/secret which base64 encoded, like following.
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-credential
  namespace: kube-system
data:
  # it's ap-northeast-1 in base64 
  aws_region: YXAtbm9ydGhlYXN0LTE=
  # AKIAIOSFODNN7EXAMPLE
  aws_access_key_id:  QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  # wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  aws_secret_access_key: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
```
